/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface WorkChainEscrowInterface extends Interface {
    getFunction(nameOrSignature: "approveMilestone" | "createProject" | "fundProject" | "getContractBalance" | "getMilestone" | "getMilestonesCount" | "openDispute" | "projectCounter" | "projects" | "rejectMilestone" | "submitMilestone"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisputeOpened" | "MilestoneApproved" | "MilestoneRejected" | "MilestoneSubmitted" | "ProjectCreated" | "ProjectFunded"): EventFragment;

    encodeFunctionData(functionFragment: 'approveMilestone', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createProject', values: [AddressLike, AddressLike, BigNumberish, string[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'fundProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getContractBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMilestone', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMilestonesCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'openDispute', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'projectCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'projects', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'rejectMilestone', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitMilestone', values: [BigNumberish, BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'approveMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getContractBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMilestonesCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projectCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projects', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitMilestone', data: BytesLike): Result;
  }

  
    export namespace DisputeOpenedEvent {
      export type InputTuple = [projectId: BigNumberish, milestoneIndex: BigNumberish];
      export type OutputTuple = [projectId: bigint, milestoneIndex: bigint];
      export interface OutputObject {projectId: bigint, milestoneIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneApprovedEvent {
      export type InputTuple = [projectId: BigNumberish, milestoneIndex: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [projectId: bigint, milestoneIndex: bigint, amount: bigint];
      export interface OutputObject {projectId: bigint, milestoneIndex: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneRejectedEvent {
      export type InputTuple = [projectId: BigNumberish, milestoneIndex: BigNumberish];
      export type OutputTuple = [projectId: bigint, milestoneIndex: bigint];
      export interface OutputObject {projectId: bigint, milestoneIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneSubmittedEvent {
      export type InputTuple = [projectId: BigNumberish, milestoneIndex: BigNumberish, evidenceHash: BytesLike];
      export type OutputTuple = [projectId: bigint, milestoneIndex: bigint, evidenceHash: string];
      export interface OutputObject {projectId: bigint, milestoneIndex: bigint, evidenceHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectCreatedEvent {
      export type InputTuple = [projectId: BigNumberish, client: AddressLike, worker: AddressLike, totalAmount: BigNumberish];
      export type OutputTuple = [projectId: bigint, client: string, worker: string, totalAmount: bigint];
      export interface OutputObject {projectId: bigint, client: string, worker: string, totalAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectFundedEvent {
      export type InputTuple = [projectId: BigNumberish, depositedAmount: BigNumberish];
      export type OutputTuple = [projectId: bigint, depositedAmount: bigint];
      export interface OutputObject {projectId: bigint, depositedAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface WorkChainEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): WorkChainEscrow;
    waitForDeployment(): Promise<this>;

    interface: WorkChainEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveMilestone: TypedContractMethod<
      [projectId: BigNumberish, milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createProject: TypedContractMethod<
      [worker: AddressLike, moderator: AddressLike, totalAmount: BigNumberish, milestoneTitles: string[], milestonePercentages: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >
    

    
    fundProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    getContractBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getMilestone: TypedContractMethod<
      [projectId: BigNumberish, milestoneIndex: BigNumberish, ],
      [[string, bigint, bigint, string, bigint] & {title: string, percentage: bigint, amount: bigint, evidenceHash: string, status: bigint }],
      'view'
    >
    

    
    getMilestonesCount: TypedContractMethod<
      [projectId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    openDispute: TypedContractMethod<
      [projectId: BigNumberish, milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    projectCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    projects: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, bigint, boolean] & {client: string, worker: string, moderator: string, totalAmount: bigint, depositedAmount: bigint, paidAmount: bigint, status: bigint, exists: boolean }],
      'view'
    >
    

    
    rejectMilestone: TypedContractMethod<
      [projectId: BigNumberish, milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitMilestone: TypedContractMethod<
      [projectId: BigNumberish, milestoneIndex: BigNumberish, evidenceHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveMilestone'): TypedContractMethod<
      [projectId: BigNumberish, milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createProject'): TypedContractMethod<
      [worker: AddressLike, moderator: AddressLike, totalAmount: BigNumberish, milestoneTitles: string[], milestonePercentages: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getContractBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMilestone'): TypedContractMethod<
      [projectId: BigNumberish, milestoneIndex: BigNumberish, ],
      [[string, bigint, bigint, string, bigint] & {title: string, percentage: bigint, amount: bigint, evidenceHash: string, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getMilestonesCount'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'openDispute'): TypedContractMethod<
      [projectId: BigNumberish, milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'projectCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'projects'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, bigint, boolean] & {client: string, worker: string, moderator: string, totalAmount: bigint, depositedAmount: bigint, paidAmount: bigint, status: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'rejectMilestone'): TypedContractMethod<
      [projectId: BigNumberish, milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitMilestone'): TypedContractMethod<
      [projectId: BigNumberish, milestoneIndex: BigNumberish, evidenceHash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DisputeOpened'): TypedContractEvent<DisputeOpenedEvent.InputTuple, DisputeOpenedEvent.OutputTuple, DisputeOpenedEvent.OutputObject>;
getEvent(key: 'MilestoneApproved'): TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
getEvent(key: 'MilestoneRejected'): TypedContractEvent<MilestoneRejectedEvent.InputTuple, MilestoneRejectedEvent.OutputTuple, MilestoneRejectedEvent.OutputObject>;
getEvent(key: 'MilestoneSubmitted'): TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
getEvent(key: 'ProjectCreated'): TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
getEvent(key: 'ProjectFunded'): TypedContractEvent<ProjectFundedEvent.InputTuple, ProjectFundedEvent.OutputTuple, ProjectFundedEvent.OutputObject>;

    filters: {
      
      'DisputeOpened(uint256,uint256)': TypedContractEvent<DisputeOpenedEvent.InputTuple, DisputeOpenedEvent.OutputTuple, DisputeOpenedEvent.OutputObject>;
      DisputeOpened: TypedContractEvent<DisputeOpenedEvent.InputTuple, DisputeOpenedEvent.OutputTuple, DisputeOpenedEvent.OutputObject>;
    

      'MilestoneApproved(uint256,uint256,uint256)': TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
      MilestoneApproved: TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
    

      'MilestoneRejected(uint256,uint256)': TypedContractEvent<MilestoneRejectedEvent.InputTuple, MilestoneRejectedEvent.OutputTuple, MilestoneRejectedEvent.OutputObject>;
      MilestoneRejected: TypedContractEvent<MilestoneRejectedEvent.InputTuple, MilestoneRejectedEvent.OutputTuple, MilestoneRejectedEvent.OutputObject>;
    

      'MilestoneSubmitted(uint256,uint256,bytes32)': TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
      MilestoneSubmitted: TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
    

      'ProjectCreated(uint256,address,address,uint256)': TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
      ProjectCreated: TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
    

      'ProjectFunded(uint256,uint256)': TypedContractEvent<ProjectFundedEvent.InputTuple, ProjectFundedEvent.OutputTuple, ProjectFundedEvent.OutputObject>;
      ProjectFunded: TypedContractEvent<ProjectFundedEvent.InputTuple, ProjectFundedEvent.OutputTuple, ProjectFundedEvent.OutputObject>;
    
    };
  }